# Generated by Django 5.0.2 on 2024-03-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
